env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
settings:
  import/resolver:
    typescript: {}
rules:
  "indent": ["error", 2]
  no-multiple-empty-lines:
    - error
    - max: 2
  no-param-reassign:
    - off
  lines-between-class-members:
    - off
  "@typescript-eslint/lines-between-class-members":
    - error
    - always
    - exceptAfterSingleLine: true
  no-return-assign:
    - off
  import/prefer-default-export:
    - off
